---
title: "Group document"
format: 
  html: 
    embed-resources: true
editor: visual
---

## Load Libraries

```{r}
library("tidyverse")
library("ggrepel")
library("broom")
library("patchwork")
```

## Load Data

```{r}
#| error: false
#| warning: false
biopsy <- read_csv("https://wilkelab.org/classes/SDS348/data_sets/biopsy.csv")
```

## Data Analysis

```{r}
#| error: false
#| warning: false
pca_fit <- biopsy |>
  select(where(is.numeric)) |> # retain only numeric columns
  scale() |> # scale data
  prcomp() # do PCA

pca_fit |>
  augment(biopsy) |> # add original dataset back in
  ggplot(aes(x = .fittedPC1, 
             y = .fittedPC2, 
             color = outcome)) + 
  geom_point(size = 1.5) +
  scale_color_manual(
    values = c(malignant = "#D55E00", 
               benign = "#0072B2")
  ) +
  theme_bw()+
  labs(title = "PC2 vs PC1",
       subtitle = "Stratified via outcome",
       x = "PC1",
       y = "PC2",
       color = "Outcome")

```

```{r}
pca_fit |> 
  tidy(matrix = "rotation")
```

```{r}
# define arrow style for plotting
arrow_style <- arrow(angle = 20,
                     ends = "first",
                     type = "closed",
                     length = grid::unit(8, "pt")
)

# plot rotation matrix
pca_fit |> 
  tidy(matrix = "rotation") |> 
  pivot_wider(names_from = "PC",
              names_prefix = "PC",
              values_from = "value") |> 
  ggplot(aes(PC1, PC2)) +
  geom_segment(xend = 0,
               yend = 0,
               arrow = arrow_style,
               alpha = 0.5) +
  geom_text_repel(
    aes(label = column),
    hjust = 1, nudge_x = -0.02, 
    color = "#0072B2",
    max.overlaps = 100,
    size = 3
  ) +
  xlim(-1.25, .5) + ylim(-.5, 1) +
  coord_fixed() + 
  theme_bw() + 
  labs(title = "Rotation matrix of PC2 vs PC1")
```
<<<<<<< HEAD
=======

```{r}
pca_fit |>
  tidy(matrix = "eigenvalues") |>
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#0072B2", alpha = 0.8) +
  scale_x_continuous(breaks = 1:9) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  ) +
  theme_bw() +
  labs(title = "Variance explained by each PC")
```

```{r}
#Nyt felt
```
>>>>>>> 52a026304f9f02b6b5c1548f0e0852f140a1d419
